<?php 

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_fiche-club',
		'title' => 'Fiche Club',
		'fields' => array (
			array (
				'key' => 'field_5ac5c19378d38',
				'label' => 'Infos',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5ac5c09778d35',
				'label' => 'Nom Court',
				'name' => 'nom_court',
				'type' => 'text',
				'instructions' => 'Nom du club en version abrégée (25 caractères max.)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 25,
			),
			array (
				'key' => 'field_5ac5c11078d36',
				'label' => 'Lieu de pratique',
				'name' => 'lieu_de_pratique',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5ac5c12f78d37',
				'label' => 'Icone',
				'name' => 'icone',
				'type' => 'image',
				'instructions' => 'Petite image d\'illustration',
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5ac5c1aa78d39',
				'label' => 'Coordonnées',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5ac5c1c278d3a',
				'label' => 'Adresse',
				'name' => 'adresse',
				'type' => 'text',
				'instructions' => 'Adresse du club',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_5ac5c1db78d3b',
				'label' => 'Téléphone',
				'name' => 'telephone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5ac5c1fb78d3c',
				'label' => 'E-mail',
				'name' => 'e-mail',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5ac5c21378d3d',
				'label' => 'Nom du contact',
				'name' => 'nom_du_contact',
				'type' => 'text',
				'instructions' => 'Indiquer un nom de personne référent pour le club',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5ac5c25278d3e',
				'label' => 'URL',
				'name' => '',
				'type' => 'tab',
			),
			// array (
			// 	'key' => 'field_5ac5c27978d3f',
			// 	'label' => 'URL de la fiche descriptive',
			// 	'name' => 'url_de_la_fiche_descriptive',
			// 	'type' => 'text',
			// 	'default_value' => '',
			// 	'placeholder' => '',
			// 	'prepend' => '',
			// 	'append' => '',
			// 	'formatting' => 'html',
			// 	'maxlength' => '',
			// ),
			array (
				'key' => 'field_5ac5c29178d40',
				'label' => 'URL de la page des séances',
				'name' => 'url_de_la_page_des_seances',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5ac5c2a378d41',
				'label' => 'URL de la page d\'actualités',
				'name' => 'url_de_la_page_dactualites',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5ac5c2b878d42',
				'label' => 'URL du site Internet',
				'name' => 'url_du_site_internet',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'clubs',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
